### ISSUE TITLE
How to style components?

### ISSUE THREAD

**Issue by ti10le** [marigold-ui/marigold#180]
- we need root styles in the theme (e.g. button)
- so little as possible copy and paste
- we need a structure for complex components with small differences like the button component. button (themeSection) has two variants (large, small) and we need one more level for more different implementations like: primary, secondary, ghost, disabled, ..

**Comment by sebald** [comment]
What do you mean by:

> so little as possible copy and paste

---

> we need a structure for complex components with small differences like the button component. button (themeSection) has two variants (large, small) and we need one more level for more different implementations like: primary, secondary, ghost, disabled, ..

Do we? Isn't that a user land problem? If think we should gather more experience first and then help to user to make this easier. I wonder if this is only a problem that exists with buttons.

Also, this can be solved via theme. It's just not that beautiful 😄

*Context:* We previously solved this by allowing to pass multiple `variants` to the `css` prop. E.g. `<Box variant={['button.primary', 'button.large']} />`. This only worked because the "primary" part controlled color values and the "large" part controlled size values.

**Comment by ti10le** [comment]
copy/paste: It's nearly the same like that we need some root styles. 

--> Yes we can do it first with a way like this. Later we can talk about a better way.
