### ISSUE TITLE
Make `Columns#collapseAt` prop accept breakpoints

### ISSUE THREAD

**Issue by michael-p** [marigold-ui/marigold#2330]
## Description

It would be great if one could pass "magic" values to the `collapseAt` of `Columns` so that it collapses at the breakpoint values specified by the current theme, e.g. `<Columns collapseAt="breakpoint-1"> ... </Columns>`. Currently, only concrete values like `54em` are allowed. 

## Context

Many layouts require the collapsing exactly at the specified breakpoints (e.g. when also using `useResponsiveValue`).

**Comment by sebald** [comment]
Possible solutions:

1. Introduce `collspseAtBreakpoint` prop that only accepts breakpoints. Downside: nicht be confusing since we can only use one collapse prop.

2. Allow `string | number` for `collapseAt` prop. Strings will be used directly. Numbers will map to the corresponding breakpoint index.

**Comment by sebald** [comment]
@michael-p can we close this? 🤔

**Comment by michael-p** [comment]
Well I still think it would be nice to have this (we need it in ACC) but should be possible to work around this now that https://github.com/marigold-ui/marigold/issues/2331 is fixed, so feel free to close as wont-fix/wont-do :)
