### ISSUE TITLE
Design & component update - Select

### ISSUE THREAD

**Issue by ti10le** [marigold-ui/marigold#913]
Current Version:
- simple Select component with variant prop

-> [Figma Design](https://www.figma.com/file/DFKyTGHAoDxOsUBPszLLxP/%F0%9F%8F%B5%EF%B8%8FMarigold?node-id=457%3A0)

**Todo**:
- show select as expected in the figma design
- add error prop to make outline red and show Validation Message
- add focused and disabled
- add hover and selected

**Comment by ti10le** [comment]
first changes for this issue in #1146

**Comment by ti10le** [comment]
ToDo:
- Item defaultSelected
- Item disabled
- show select as expected in the figma design: borders when open listBox, button and listbox every time the same width

**Comment by ti10le** [comment]
- error and required prop --> in review
- itemSelected and disabledItem --> almost finished

**Comment by viktoria-schwarz** [comment]
- The select field "jumps" when you open it (border instead of outline)
- If you open the dropdown on the bottom of the page and the ListBox is displayed above, the borders are wrong
- What if you want to unselect an item/select "none"? (display placeholder as option, optionally)
- on error: doesn't it make more sense to remove the red border when listbox is opened and only display the red border when the focus is NOT on the select?
- use `<Select>` on docs page for ThemeSwitch


@ti10le @sebald what do you think, how close should we stick to the Figma design?

**Comment by sebald** [comment]
As close as possible? 😄

**Comment by viktoria-schwarz** [comment]
Well :D I find it difficult if it doesn't cover all cases, but fine

**Comment by sebald** [comment]
Yeah, I mean we *should* get 100%!

**Comment by ti10le** [comment]
fix todo: styling if select listbox opens above the select button.

**Comment by ti10le** [comment]
#1225 bugfix for jumping Select component borders
